
  - name: Playbook
    hosts: host
    become: yes
    become_user: root
    tasks:
      - name: Update and upgrade apt packages
        become: true
        apt:
          update_cache: yes
          cache_valid_time: 86400 #One day
      - name: install docker
        apt:
          name: docker.io
          state: present
      - name:  install open-jdk
        apt:
          name: default-jdk-headless
          state: present
        
      - name: copy jenkins agent file
        copy:
          src: agent.jar
          dest: /home/ubuntu

      - name: copy app env file agent file
        copy:
          src: .env
          dest: /home/ubuntu
      - name: adding user to group docker
        user:
          name: "ubuntu"
          groups: docker
          append: yes
