
  - name: Playbook
    hosts: host
    become: yes
    become_user: root
    tasks:
      - name: Update  apt packages
        become: true
        apt:
          update_cache: yes
          cache_valid_time: 86400 #One day
      - name: install docker
        apt:
          name: docker.io
          state: present
      - name:  install open-jdk
        apt:
          name: default-jdk-headless
          state: present
        
      - name: copy jenkins agent.jar to slave
        copy:
          src: agent.jar
          dest: /home/ubuntu

      - name: copy env file to slave
        copy:
          src: .env
          dest: /home/ubuntu
      - name: running docker without sudo  
        user:
          name: "ubuntu"
          groups: docker
          append: yes
